src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $post_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPostAt(): ?string
    {
        return date_format($this->post_at, 'm-d-Y à H:i:s');
    }

    public function setPostAt(\DateTimeImmutable $post_at): self
    {
        $this->post_at = $post_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 150)]
    private ?string $pseudo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }
}

src/Controller/PhotoController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use DateTimeImmutable;
use App\Repository\PhotoRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PhotoController extends AbstractController
{
    #[Route('/', name: 'photo.list')]
    public function list(PhotoRepository $photoRepository): Response
    {
        // return $this->render('photo/list.html.twig', [
        //     'controller_name' => 'PhotoController',
        // ]);

        // $photo = new Photo(); 
        // $photo->setTitle('Ma première photo'); 
        // $photo->setPostAt( new DateTimeImmutable()); 
        // $photos = [] ; 
        // $photos[] = $photo ; 

        $photos = $photoRepository->findAll(); 

        return $this->render('photo/list.html.twig', ['photos' => $photos]) ; 

    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    #[Route('/user', name: 'app_user')]
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}
				Review Photo
			{% endblock %}
		</title>
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>


	<body>
		<header class="jumbotron text-center">
			<div class="row">
				<div class="col-8">
					<h1>
						Commenter des photos
					</h1>
				</div>
				<div class="col-4">
					<h5>
						Date :
						{{ "now"|date("d/m/Y") }}
					</h5>
					{% block connexion %}
						{% if not app.user %}
							<a href="{{ path("app_login") }}" class="btn btn-primary">
								Se connecter
							</a>
						{% else %}
							<h4>
								Bienvenue :
								{{ app.user.pseudo }}
							</h4>
							<a href="{{ path('app_logout') }}" class="btn btn-secondary">
								Se déconnecter
							</a>
						{% endif %}
					{% endblock %}
				</div>
			</div>
		</header>

		<nav class="navbar navbar-dark bg-dark mb-2">
			<a class="navbar-brand" href="{{ path("photo.list") }}">Home</a>
		</nav>

		{% block body %}
		{% endblock %}
	</body>
</html>

templates/photo/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Liste des Photos
{% endblock %}

{% block body %}
	<div class="container">
		<h2>
			Les photos
		</h2>
		<div class="row flex">
			{% for photo in photos %}
				<div class="col-3">
					<div class="card">
						<img class="card-img-top" src="{{ asset('assets/photos/empty.jpg') }}" alt="img defaut">
						<div class="card-boby">
							<h5 class="card-title">
								<a href="">
									{{ photo.title }}
								</a>
							</h5>
							<h5>
								Postée par : {{photo.user.pseudo}}
							</h5>
							<p class="card-text">
								Postée le :
								{{ photo.postAt }}
							</p>
							<div class="text-primary" style="font-weight: bold; font-size: 1.2rem;">
								commentaires : 0
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>

{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block connexion %}{% endblock %}

{% block body %}

<form method="post">

    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            Vous êtes connecté en tant que {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Se déconnecter</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal mt-3">Entrez vos identifiants</h1>
    <label class="mt-3 mb-2" for="inputEmail">Votre Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label class="mt-3 mb-2" for="inputPassword">Votre Mot de passe</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary mt-5" type="submit">
        Valider
    </button>
</form>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/projets_symfony/ReviewPhoto/src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/projets_symfony/ReviewPhoto/templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}